verify exit code of beaker job (#187)
* verify exit code of beaker job

* fix image name in build job

* force it to fail for testing

* revert forced fail

* fix

* finalize

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -281,18 +281,30 @@ jobs:
       - name: Submit beaker job
         run: |
           EXPERIMENT=$(beaker experiment create beaker_config.yml --workspace $BEAKER_WORKSPACE --name gpu-tests-$COMMIT_SHA | awk '{print $2}')
-          echo "EXPERIMENT=$EXPERIMENT" >> $GITHUB_ENV
-          echo "Experiment $EXPERIMENT submitted. See progress at https://beaker.org/ex/$EXPERIMENT"
+          if [ -z "$EXPERIMENT" ]; then
+            exit 1
+          else
+            echo "EXPERIMENT=$EXPERIMENT" >> $GITHUB_ENV
+            echo "Experiment $EXPERIMENT submitted. See progress at https://beaker.org/ex/$EXPERIMENT"
+          fi
 
       - name: Wait for job to finish
         run: |
           beaker experiment await $EXPERIMENT tests finalized --timeout 10m
+          # Check the job's exit code.
+          test $(beaker experiment get $EXPERIMENT --format=json | jq '.[0].jobs[0].status.exitCode') -eq 0
 
       - name: Get logs
         if: always()
         run: |
+          if [ -z "$EXPERIMENT" ]; then
+            echo "No logs to show"
+            exit 0
+          fi
           beaker experiment results $EXPERIMENT --prefix out.log --output results
-          cat results/tests/out.log
+          if [ if results/tests/out.log ]; then
+            cat results/tests/out.log
+          fi
 
   release:
     name: Release
