test run

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -191,10 +191,77 @@ jobs:
           . .venv/bin/activate
           pip uninstall -y ai2-tango
 
+  gpu_tests:
+    runs-on: [ubuntu-latest]
+    env:
+      BEAKER_TOKEN: ${{ secrets.BEAKER_TOKEN }}
+      BEAKER_WORKSPACE: ai2/tango-testing
+      IMAGE_NAME: tango-testing
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Determine current commit SHA (pull request)
+        if: github.event_name == 'pull_request'
+        run: |
+          echo "COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
+
+      - name: Determine current commit SHA (push)
+        if: github.event_name != 'pull_request'
+        run: |
+          echo "COMMIT_SHA=$GITHUB_SHA" >> $GITHUB_ENV
+
+      - name: Install beaker client
+        if: github.event_name != 'pull_request'
+        shell: bash
+        run: |
+          mkdir -p "$HOME/bin"
+
+          # Download and install from latest GitHub release.
+          curl -s https://api.github.com/repos/allenai/beaker/releases/latest \
+            | grep 'browser_download_url.*linux' \
+            | cut -d '"' -f 4 \
+            | wget -qi - \
+          && tar -xvzf beaker_linux.tar.gz -C "$HOME/bin"
+
+          # Add to path.
+          echo "$HOME/bin" >> "$GITHUB_PATH"
+
+      - name: Verify beaker install
+        if: github.event_name != 'pull_request'
+        run: |
+          if [[ $(beaker account whoami | grep "ai2") == "" ]]; then
+              echo "Error: the Beaker user is not 'ai2' but should be."
+              exit 1
+          fi
+
+      - name: Create beaker experiment config
+        run: |
+          cat >beaker_config.yml << EOL
+          version: v2-alpha
+          description: GPU Tests - $COMMIT_SHA
+          tasks:
+            - name: Tests
+              image:
+                beaker: ai2/tango-testing
+              command: [tango, info]
+              result:
+                path: '/unused'
+              resources:
+                gpuCount: 2
+              context:
+                cluster: ai2/tango-gpu-tests
+                priority: normal
+          EOL
+          cat beaker_config.yml
+
+      - name: Create beaker experiment config
+        run: |
+          beaker experiment create beaker_config.yml --workspace $BEAKER_WORKSPACE --name gpu-tests-$COMMIT_SHA
+
   release:
     name: Release
     runs-on: ubuntu-latest
-    needs: [checks]
+    needs: [checks, gpu_tests]
     if: startsWith(github.ref, 'refs/tags/')
     steps:
       - uses: actions/checkout@v1
